### ISSUE TITLE
Unification of NiChart

### ISSUE THREAD

**Issue by spirosmaggioros** [CBICA/NiChart_Project#2]
### High priority unification of seperate repositories to NiChart
- Unification includes repositories that work as pipelines and are not a seperate package themselves. 
- The unification will have to come with documentation for the user to navigate through the repo with ease, this is mostly done in README files of the other repos, but some manual documentation with code comments or markdown files would be great. 
- Sphinx auto-doc will collect all the docs and create a full documentation that will provide guidance to each single element of the project.

### Repositories to be unified:
#TODO write down the repos that should be unified: @AlexanderGetka-cbica @gurayerus

### Workflows and runner:
To finilize the unification, @spirosmaggioros should add unit tests and workflows for any python version to make sure the whole pipeline works. In the workflows, we have to make sure that the packages like spare and SurrealGAN will be cloned to work properly. 

```[tasklist]
### Tasks
- [x] Check repos that should be unified
- [ ] Unify the repos(documentation or pipelines) and make sure that they work properly with unit tests and dependency checking
- [x] Create workflows for generic runs and run all the unit tests recursively
- [ ] Add manual documentation with markdown files and make sure sphinx creates a fully consise documentation for the users
- [ ] separate open/private assets from NiChart_Project_Resources
- [ ] migrate private assets to PennBox
- [x] Update submodules(some of them fail to clone)
- [x] Add requirements.txt and make sure they work for every package that NiChart_Workflows need
- [ ] add nnUNet folder to gitlab and clone it automatically or let user define nnUNet path to dir and run it this way
```

**Comment by euroso97** [comment]
Hi, can you please add a  task "separate open/private assets from NiChart_Project_Resources" & migrate private assets to PennBox?
